### ISSUE TITLE
how were the vector-formed features extracted.

### ISSUE THREAD

**Issue by sos1sos2Sixteen** [my-yy/sl_icmr2022#1]
i am wondering which specific ECAPA-TDNN and Inception model were used for the provided preprocessed dataset? Are they publicly available? and what preprocess techniques were involved in extracting these features?

**Comment by my-yy** [comment]
Hello, I used https://github.com/timesler/facenet-pytorch for the inception model.
The ECAPA-TDNN is based on [SpeechBrain](https://huggingface.co/speechbrain/spkrec-ecapa-voxceleb). While the SpeechBrain's model is trained with vox1+vox2, thus I retrained it with vox2 only.
I need some time to find the processing script and the checkpoint.
If there are no accidents, I will update the repository this week.

**Comment by sos1sos2Sixteen** [comment]
> Hello, I used https://github.com/timesler/facenet-pytorch for the inception model. The ECAPA-TDNN is based on [SpeechBrain](https://huggingface.co/speechbrain/spkrec-ecapa-voxceleb). While the SpeechBrain's model is trained with vox1+vox2, thus I retrained it with vox2 only. I need some time to find the processing script and the checkpoint. If there are no accidents, I will update the repository this week.

many many thanks for your very helpful reply!
