### ISSUE TITLE
Request to host model checkpoints on a more accessible platform

### ISSUE THREAD

**Issue by jclarke98** [my-yy/sl_icmr2022#2]
Hi there,

The ECAPA-TDNN model checkpoints on Baidu seem to be inaccessible to non-Chinese users due to the Chinese mobile number requirement for account creation. Could you host them on a more accessible platform like Google Drive or Dropbox?

Thanks!

**Comment by my-yy** [comment]
I just add a Google Drive link :)

**Comment by jclarke98** [comment]
Thank you 

> I just add a Google Drive link :)

Cool thanks
